[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.9.2",
    "openai>=1.54.3",
    "plotly>=5.24.1",
    "seaborn>=0.13.2",
    "streamlit>=1.40.0",
]
